services:
  web:
    build: .
    expose:
      - "5001"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  
  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  nginx:
    image: nginx:latest
    ports:
      - "5001:5001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
    redis-data: